language: node_js
node_js:
  - "lts/*"
  - "node"

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - npm install

script: npm run test:ci

after_success:
  - npm run codecov
